### ISSUE TITLE
Compile error (libcore)

### ISSUE THREAD

**Issue by k0pernicus** [mark-i-m/os1#1]
Hi!

Nice job :-)

I wanted to compile and run your project, but the `make` command (in the _root_ folder) gave me that: 

rustc --target=../i686-unknown-elf.json -L . --crate-type=rlib -C opt-level=3 -Z no-landing-pads rust/src/libcore/lib.rs  
rust/src/libcore/atomic.rs:200:15: 200:17 error: expected identifier, found keyword `fn`  
rust/src/libcore/atomic.rs:200     pub const fn new(v: bool) -> AtomicBool {
                                             ^~  

rust/src/libcore/atomic.rs:200:18: 200:21 error: expected `:`, found `new`  
rust/src/libcore/atomic.rs:200     pub const fn new(v: bool) -> AtomicBool {

Can you give me some explanations about that error please?

Thanks!

**Comment by mark-i-m** [comment]
Hey!

Thanks!

Can you please post the output of `git submodule` in the root directory?

**Comment by k0pernicus** [comment]
Sure - this is the output : -e66653bee52b87ada8d591b13b915e5ed2c86d5a deps/rust

Thanks!

**Comment by mark-i-m** [comment]
How about `rustc --version` ?

**Comment by k0pernicus** [comment]
this is the output : rustc 1.1.0 (35ceea399 2015-06-19)

**Comment by k0pernicus** [comment]
So... i must to upgrade my rust compiler version to 1.2 no? :-/

**Comment by mark-i-m** [comment]
Actually, I'm using an older one myself:

```
$ rustc --version
rustc 1.1.0-dev (built 2015-05-10)
```

Rust's libcore is unstable and often changes. For normal rust projects you're really supposed to use libstd, but since this was a kernel, I wanted to minimize library code.

I would try using an [older compiler](http://www.rust-lang.org/install.html). After downloading, you can use this command to install an older version (run this from the root of the downloaded and unzipped folder):

```
rustup.sh --channel=nightly --date=[date-of-relevant-release]
```

**Comment by mark-i-m** [comment]
Try the build from 2015-05-10 and let me know what happens

**Comment by k0pernicus** [comment]
Oh, ok! Thank you!
Changes in libcore are so bad... All projects i would to compile & run have failed yet 'cause that error :-/
I try this now!

**Comment by mark-i-m** [comment]
Yeah, it took me a really long to get anything to compile too. I got a lot of pointers from a friend (https://github.com/krzysz00/rust-kernel).

**Comment by k0pernicus** [comment]
Hmmm... It seems the 2015-05-10 contains only nightly versions, no?
http://static.rust-lang.org/dist/2015-05-10/index.html

**Comment by mark-i-m** [comment]
Yes, you need to use a nightly version to use unstable features like nostd (which are needed for a kernel). Also, I forgot to mention that you can find the `rustup.sh` script here: https://static.rust-lang.org/rustup.sh

**Comment by k0pernicus** [comment]
I've already downloaded the rust script to upgrade the compiler. Let's see...

**Comment by k0pernicus** [comment]
Did you use the libcore from the 2015-05 too?

**Comment by mark-i-m** [comment]
Yes, but that should already be taken care of. The submodule commit you indicated above works with the 2015-05 compiler on my machine.

**Comment by k0pernicus** [comment]
Unfortunately...

rustc --target=../i686-unknown-elf.json -L . --crate-type=rlib -C opt-level=3 -Z no-landing-pads rust/src/libcore/lib.rs  
rust/src/libcore/atomic.rs:200:15: 200:17 error: expected identifier, found keyword `fn`  
rust/src/libcore/atomic.rs:200     pub const fn new(v: bool) -> AtomicBool {
                                             ^~
rust/src/libcore/atomic.rs:200:18: 200:21 error: expected `:`, found `new`  
rust/src/libcore/atomic.rs:200     pub const fn new(v: bool) -> AtomicBool {
                                                ^~~  
Makefile:12 : la recette pour la cible « libcore.rlib » a échoué  
make[1]: **\* [libcore.rlib] Erreur 101

**Comment by k0pernicus** [comment]
(with the build `rustc 1.1.0-nightly (dc630d01e 2015-05-09) (built 2015-05-10)`)

**Comment by mark-i-m** [comment]
Hmm... This is strange.

The following seems to work for me on a clean Ubuntu 14.04 virtual machine and on my local machine (arch linux):

```
curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly --date=2015-05-10
git clone https://github.com/mark-i-m/os1.git
cd os1/
make rungraphic
```

Could you try completely uninstalling rust (`rustup.sh --uninstall`) and running the commands above?

**Comment by k0pernicus** [comment]
Same commands (with the uninstall command before, and the copy of the rust directory in deps/) and the same bug...
My OS is an ArchLinux too (LTS kernel)

**Comment by mark-i-m** [comment]
Ooops. Sorry, I forgot.

Instead of copying the rust directory into deps/, use `git submodule init && git submodule update` from the root directory. This clones the directory _and_ checks out the correct version.

**Comment by mark-i-m** [comment]
```
curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly --date=2015-05-10
git clone https://github.com/mark-i-m/os1.git
cd os1/
git submodule init && git submodule update
make rungraphic
```

**Comment by k0pernicus** [comment]
Yeah! It works!!! \o/
Thanks a lot!!!
